# This is a basic workflow to help you get started with Actions

name: Deploy to Hosting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Hugo setup
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: latest
          extended: false

      - name: Get sourcecode
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Check vesion, configuration and path content
        run: |
          hugo version
          pwd
          ls -l
          hugo config

      - name: Build
        run: hugo --minify

      - name: CNAME Config
        run: echo "godex.dev" >> public/CNAME

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_GODEX_WWW_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'go-dex-dev'
          destination-repository-name: 'www'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          user-email: developer@pacotorrado.com
          target-branch: main

